eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-serv:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true        
  instance:
    preferIpAddress: true

    